// src/components/partials/Header/index.tsx
import MainMenu from '@components/parts/MainMenu';
import { SignInButton, SignedOut } from '@clerk/nextjs';
import { auth } from '@clerk/nextjs/server';
import styles from './styles.module.css'
import type { MenuItem } from '@ts/global';

// TODO Fix menu sections
const menuItems: MenuItem[] = [
	{
		label: `Home`,
		link: `/`,
	},
	{
		label: `Meals`,
		items: [
			{
				label: `Recipes`,
				link: `/recipes`,
			},
			{
				label: `Meal Planner`,
				link: `/meals/planning`,
				auth: true
			},
			{
				label: `Shopping List`,
				link: `/meals/list`,
				auth: true
			}
		]
	},
	{
		label: `To Do`,
		link: `/tasks`,
		auth: true
	},
	{
		label: `Calendar`,
		link: `/calendar`,
		auth: true
	},
	{
		label: `Reference`,
		link: `/reference`,
		auth: true
	}
]; 


const Header = () => {
	const isAuthenticated = !!auth()?.sessionId

	return (
		<header className={styles.header}>
			<a href="/" className={styles.title}>🏡</a>
			<MainMenu
				menuItems={menuItems}
				isAuthenticated={isAuthenticated}
			>
				<SignedOut>
					<li>
						<SignInButton />
					</li>
				</SignedOut>
			</MainMenu>
		</header>
	);
};

export default Header;

// src/lib/components/partials/Header.svelte
<script lang="ts">
	import MainMenu from '$parts/MainMenu.svelte';
	import { isAuthenticated, clerk } from '$lib/auth';
	import type { MenuItem } from '$types/global';

	const menuItems: MenuItem[] = [
		{
			label: 'Home',
			link: '/',
		},
		{
			label: 'To Do',
			link: '/tasks',
			auth: true,
		},
		{
			label: 'Calendar',
			link: '/calendar',
			auth: true,
		},
		{
			label: 'Recipes',
			link: '/recipes'
		},
		{
			label: 'Meal Plan',
			link: '/meal-plan',
			auth: true,
		},
		{
			label: 'Shopping List',
			link: '/shopping-list',
			auth: true,
		},
		{
			label: 'Reference',
			link: '/reference',
			auth: true,
		},
		{
			label: 'Small Human',
			link: '/small-human',
			auth: true,
		},
	];

	function handleSignIn() {
		$clerk?.redirectToSignIn();
	}
</script>

<header class="header">
	<a href="/" class="title">🏡</a>
	<MainMenu {menuItems} isAuthenticated={$isAuthenticated}>
		{#if !$isAuthenticated}
			<li>
				<button onclick={handleSignIn}>Sign in</button>
			</li>
		{/if}
	</MainMenu>
</header>

<style>
	@import '@mixins';

	.header {
		@include container_spacing;

		display: flex;
		flex-wrap: wrap;
		align-items: center;
		justify-content: space-between;
		font-size: 1.2em;
		font-weight: 700;
		grid-area: header;
	}

	.title {
		display: block;
		font-size: 3em;
		text-decoration: none;
	}
</style>
