// src/components/parts/tasks/Kanban/index.tsx
import TaskCard from "@components/parts/tasks/Task"
import styles from './styles.module.css'
import type { Task, TaskStatus } from "@ts/tasks"
import type { CSSProperties } from "react"

type TaskViewProps = {
	tasks: Task[]
}

const TaskBoard = (props: TaskViewProps) => {
	const { tasks = [] } = props
	const parsedTasks: Record<string, Task[]> = {}

	tasks.forEach(task => {
		if(!parsedTasks[task.status]) parsedTasks[task.status] = []

		parsedTasks[task.status].push(task)
	})

	return (
		<div className={styles.board} style={{'--columns': Object.keys(parsedTasks).length } as CSSProperties}>
			{Object.entries(parsedTasks).map(([status, tasks]) => (
				<div className={styles.column} key={status}>
					<h2>{status}</h2>
					<ul className={styles.list}>
						{tasks.map(task => (
							<li className={styles.item} key={task.id}>
								<TaskCard {...task} />				
							</li>
						))}
					</ul>
				</div>
			))}
		</div>
	)
}

export default TaskBoard

// src/lib/components/parts/tasks/Kanban.svelte
<script lang="ts">
	import TaskCard from './Task.svelte';
	import type { Task, TaskStatus } from '$types/tasks';

	let {
		tasks = [],
		onUpdate,
	}: { tasks: Task[]; onUpdate?: (id: string, status: TaskStatus) => void } = $props();

	let parsedTasks = $derived.by(() => {
		const grouped: Record<string, Task[]> = {};
		tasks.forEach((task) => {
			if (!grouped[task.status]) grouped[task.status] = [];
			grouped[task.status].push(task);
		});
		return grouped;
	});

	let columnCount = $derived(Object.keys(parsedTasks).length);
</script>

<div class="board" style="--columns: {columnCount}">
	{#each Object.entries(parsedTasks) as [status, statusTasks] (status)}
		<div class="column">
			<h2>{status}</h2>
			<ul class="list">
				{#each statusTasks as task (task.id)}
					<li class="item">
						<TaskCard {...task} {onUpdate} />
					</li>
				{/each}
			</ul>
		</div>
	{/each}
</div>

<style>
	.board {
		gap: 10px;
		display: grid;
		grid-template-columns: repeat(var(--columns), minmax(100px, 1fr));
	}

	.list {
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.item {
		margin: 0.3em 0;
	}
</style>
