// src/components/parts/tasks/List/index.tsx
import TaskCard from "@components/parts/tasks/Task"
import styles from './styles.module.css'
import type { Task } from "@ts/tasks"

type TaskViewProps = {
	tasks: Task[]
}

const TaskList = (props: TaskViewProps) => {
	const { tasks = [] } = props
	return (
		<ul className={styles.list}>
			{tasks.map(task => (
				<li className={styles.item} key={task.id}>
					<TaskCard {...task} />				
				</li>
			))}
		</ul>
	)
}

export default TaskList

// src/lib/components/parts/tasks/List.svelte
<script lang="ts">
	import TaskCard from './Task.svelte';
	import type { Task } from '$types/tasks';

	let { tasks = [] }: { tasks: Task[] } = $props();
</script>

<ul class="list">
	{#each tasks as task (task.id)}
		<li class="item">
			<TaskCard {...task} />
		</li>
	{/each}
</ul>

<style>
	.list {
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.item {
		margin: 0.3em 0;
	}
</style>
