// src/app/calendar/page.tsx
import Calendar from '@components/parts/calendar/calendar';
import parseCalendars from '@utils/calendar/parseCalendarFeeds';
import parseTasks from '@utils/calendar/parseTasks';
import fetchData from '@utils/fetchData';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Calendar',
	description: 'View combined calendars and tasks for the family',
};

export default async function CalendarPage ()
{
	const { tasks = [], calendars = [] } = await fetchData({
		authenticated: true,
		gqlQuery: `
			query {
				tasks {
					id
					name
					assigned {
						name
						slug
						profile
						colour
					}
					status
					due
					estimate
					link
					platform
				}
				calendars {
					name
					url
					colour
					slug
				}
			}
		`
	});



	let events = []

	const taskEvents = parseTasks(tasks);

	events.push(...taskEvents);


	await parseCalendars(calendars)
		.then(res => {
			events.push(...res)
		});

	return ( 
		<>
			<h1>Calendar</h1>
			<Calendar events={events} />
		</>
	)
}

// src/routes/calendar/+page.svelte
<script lang="ts">
	import CalendarView from '$partials/Calendar.svelte';
	import { isAuthenticated } from '$lib/auth';
	import fetchClientData from '$utils/fetchClientData';
	import type { Task } from '$types/tasks';

	let tasks = $state<Task[]>([]);
	let events = $state<any[]>([]);
	let icalEvents = $state<any[]>([]);
	let mealPlans = $state<any[]>([]);
	let loading = $state(true);

	$effect(() => {
		if ($isAuthenticated) {
			fetchClientData({
				cacheKey: 'calendar',
				gqlQuery: `
					query {
						tasks {
							id
							name
							assigned {
								name
								slug
								profile
								colour
							}
							status
							due
							estimate
							link
							platform
						}
						events {
							name
							dates {
								start
								end
							}
							status
							id
						}
					}
				`,
			}).then((res) => {
				tasks = res.tasks ?? [];
				events = res.events ?? [];
				loading = false;
			});

			fetchClientData({
				cacheKey: 'icsEvents',
				gqlQuery: `
					query {
						icsEvents {
							id
							name
							dates {
								start
								end
							}
							status
							allDay
							colour
						}
					}
				`,
			}).then((res) => {
				icalEvents = res.icsEvents ?? [];
			});

			fetchClientData({
				cacheKey: 'calendar-mealplans',
				gqlQuery: `
					query {
						mealPlans(perPage: 50, orderBy: "date", orderDirection: "asc") {
							items {
								id date entryType title
								recipe { name slug }
							}
						}
					}
				`,
			}).then((res) => {
				mealPlans = res.mealPlans?.items ?? [];
			});
		}
	});
</script>

<svelte:head>
	<title>Calendar | Kapers Crewe Household</title>
	<meta name="description" content="View combined calendars and tasks for the family" />
</svelte:head>

<h1>Calendar</h1>
{#if loading}
	<p>Loading...</p>
{:else}
	<CalendarView {tasks} allDayEvents={events} {icalEvents} {mealPlans} />
{/if}
