// src/lib/components/parts/tasks/Assigned/index.svelte
<script lang="ts">
	import type { User } from '$types/global';
	import styles from './index.module.css';

	let { assignees = [], class: className = '' }: { assignees: User[]; class?: string } = $props();
</script>

<ul class="{styles.list} {className}">
	{#each assignees as { slug, name, profile } (slug)}
		<li class={styles.item}>
			<span class="sr-only">{name}</span>
			{#if profile}
				<img class={styles.image} src={profile} alt="" />
			{:else}
				<span class={styles.image}>
					{name
						.split(' ')
						.map((word) => word[0])
						.join('')}
				</span>
			{/if}
		</li>
	{/each}
</ul>

// src/components/parts/tasks/Assigned/index.tsx
import styles from './styles.module.css'
import type { User } from "@ts/global"

type AssignedProps = {
	assignees: User[]
	className?: string
}

const Assignees = (props: AssignedProps) => {
	const { assignees = [], className = `` } = props
	return (
		<ul
			className={`${className} ${styles.list}`}
		>
			{assignees.map(({ slug, name, profile }) => (
				<li key={slug} className={styles.item}>
					<span className="sr-only">{name}</span>
					{profile ?
						<img className={styles.image} src={profile} alt="" />
						:	<span className={styles.image}>
							{name.split(` `).map(word => word[0]).join(``)}
						</span>
					}
				</li>
			))}
		</ul>
	)
}

export default Assignees
