// src/lib/components/layouts/Default/index.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import './index.module.css';

	let { children, wide = false, full = false, class: className = '' }: { children: Snippet; wide?: boolean; full?: boolean; class?: string } = $props();
</script>

<div
	class="layout {className}"
	class:wide
	class:full
>
	{@render children()}
</div>

// src/components/layouts/default/index.tsx
import styles from './styles.module.css'
import type { ReactNode } from 'react'

type LayoutProps = {
	children: ReactNode
	fullWidth?: boolean
}

const Layout = (props: LayoutProps) => {
	const { children, fullWidth } = props

	return (
		<div className={[styles.layout, fullWidth && styles.full].join(` `)}>
			{children}
		</div>
	)
}

export default Layout
