// src/app/(app)/tasks/page.tsx
import TaskList from '@components/parts/tasks/TaskView';
import fetchData from '@utils/fetchData';
import type { Task } from '@ts/tasks';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: `Tasks`,
	description: `View all upcoming and overdue tasks in various views`,
};

export default async function CalendarPage () {
	const { tasks = [] } = await fetchData({
		authenticated: true,
		gqlQuery: `
			query {
				tasks {
					id
					name
					assigned {
						name
						id
						profile
					}
					status
					due
				}
			}
		`
	}) as { tasks: Task[]}

	return ( 
		<>
			<h1>Tasks</h1>
			<TaskList tasks={tasks} />
		</>
	)
}

// src/routes/tasks/+page.svelte
<script lang="ts">
	import TaskView from '$parts/tasks/TaskView.svelte';
	import { isAuthenticated } from '$lib/auth';
	import fetchClientData from '$utils/fetchClientData';
	import type { Task } from '$types/tasks';


	let tasks = $state<Task[]>([]);
	let loading = $state(true);

	$effect(() => {
		if ($isAuthenticated) {
			function handleTasks(res: any) {
				tasks = res.tasks ?? [];
				loading = false;
			}
			fetchClientData({
				cacheKey: 'tasks',
				onStale: handleTasks,
				gqlQuery: `
					query {
						tasks {
							id
							name
							assigned {
								name
								profile
							}
							status
							due
						}
					}
				`,
			}).then(handleTasks);
		}
	});
</script>

<svelte:head>
	<title>Tasks | Kapers Crewe Household</title>
	<meta name="description" content="View all upcoming and overdue tasks in various views" />
</svelte:head>

<h1>Tasks</h1>
{#if loading}
	<p>Loading...</p>
{:else}
	<TaskView {tasks} />
{/if}
