// src/lib/components/parts/tasks/List/index.svelte
<script lang="ts">
	import TaskCard from '../Task/index.svelte';
	import type { Task, TaskStatus } from '$types/tasks';
	import styles from './index.module.css';

	let {
		tasks = [],
		onUpdate,
		class: className = '',
	}: { tasks: Task[]; onUpdate?: (id: string, status: TaskStatus) => void; class?: string } = $props();
</script>

<ul class="{styles.list} {className}">
	{#each tasks as task (task.id)}
		<li class={styles.item}>
			<TaskCard {...task} {onUpdate} />
		</li>
	{/each}
</ul>

// src/components/parts/tasks/List/index.tsx
import TaskCard from "@components/parts/tasks/Task"
import styles from './styles.module.css'
import type { Task } from "@ts/tasks"

type TaskViewProps = {
	tasks: Task[]
}

const TaskList = (props: TaskViewProps) => {
	const { tasks = [] } = props
	return (
		<ul className={styles.list}>
			{tasks.map(task => (
				<li className={styles.item} key={task.id}>
					<TaskCard {...task} />				
				</li>
			))}
		</ul>
	)
}

export default TaskList
