// src/lib/components/parts/tasks/TaskView/index.svelte
<script lang="ts">
	import TaskList from '../List/index.svelte';
	import TaskBoard from '../Kanban/index.svelte';
	import TaskCalendar from '../TaskCalendar/index.svelte';
	import type { Task, TaskStatus } from '$types/tasks';
	import type { Component } from 'svelte';
	import styles from './index.module.css';

	let {
		tasks = [],
		onUpdate,
		class: className = '',
	}: { tasks: Task[]; onUpdate?: (id: string, status: TaskStatus) => void; class?: string } = $props();

	type TaskViewType = 'list' | 'kanban' | 'calendar';

	const views: Record<
		TaskViewType,
		{ component: Component<{ tasks: Task[]; onUpdate?: (id: string, status: TaskStatus) => void }>; name: string }
	> = {
		list: {
			component: TaskList,
			name: 'List',
		},
		kanban: {
			component: TaskBoard,
			name: 'Kanban',
		},
		calendar: {
			component: TaskCalendar,
			name: 'Calendar',
		},
	};

	let view = $state<TaskViewType>('calendar');
</script>

<div class={className}>
	<nav class={styles.switcher}>
		{#each Object.entries(views) as [viewType, { name }] (viewType)}
			<button onclick={() => (view = viewType as TaskViewType)} data-active={view === viewType}>
				{name}
			</button>
		{/each}
	</nav>
	{#if view === 'list'}
		<TaskList {tasks} {onUpdate} />
	{:else if view === 'kanban'}
		<TaskBoard {tasks} {onUpdate} />
	{:else}
		<TaskCalendar {tasks} {onUpdate} />
	{/if}
</div>

// src/components/parts/tasks/TaskView/index.tsx
'use client'

import type { Task } from "@ts/tasks"
import styles from './styles.module.css'
import { useState } from "react"
import TaskList from "@parts/tasks/List"
import TaskBoard from '@parts/tasks/Kanban'
import TaskCalendar from '@parts/tasks/Calendar'

type TaskViewProps = {
	tasks: Task[]
}

type TaskViewType = 'list' | 'kanban' | 'calendar'

const views: Record<TaskViewType, {
	component: React.ComponentType<TaskViewProps> | any,
	name: string
}> = {
	list: {
		component: TaskList,
		name: 'List',
	},
	kanban: {
		component: TaskBoard,
		name: 'Kanban',
	},
	calendar: {
		component: TaskCalendar,
		name: 'Calendar',
	},
}

const TaskView = (props: TaskViewProps) => {
	const { tasks = [] } = props
	const [view, setView] = useState<TaskViewType>('calendar')
	const ViewComponent = views[view].component

	return (
		<div>
			<nav className={styles.switcher}>
				{Object.entries(views).map(([viewType, {name}]) => (
					<button
						key={viewType}
						onClick={() => setView(viewType as TaskViewType)}
						data-active={view === viewType}
					>
						{name}
					</button>
				))}
			</nav>
			<ViewComponent tasks={tasks} />
		</div>
	)
}

export default TaskView
